### ISSUE TITLE
href doesnt work

### ISSUE THREAD

**Issue by kvrvgv** [Jigsaw-Code/outline-sdk#183]
this button open new tab with url `https://getoutline.org/ru/ruhttps://github.com/Jigsaw-Code/outline-sdk` 
[v](https://getoutline.org/ru/for-developers/)

![изображение](https://github.com/Jigsaw-Code/outline-sdk/assets/50778263/6b6daf95-4582-4dad-ae9b-57795600ffd2)

**Comment by fortuna** [comment]
Thanks for the report. As far as I can tell this has been fixed.
