### ISSUE TITLE
ReInstall OutLine Manager

### ISSUE THREAD

**Issue by alexsandrskopin** [Jigsaw-Code/outline-sdk#192]
"I reinstalled the operating system on my computer -> reinstalled Outline Manager. How can I get the link (**magical green line**) for connection without reinstalling the entire server?"

**Comment by jyyi1** [comment]
Hi @alexsandrskopin , could you try https://github.com/Jigsaw-Code/outline-server/issues/942#issuecomment-892549894 ? Thanks.
