### ISSUE TITLE
Any way to run Outline client on linux server terminal by command line?

### ISSUE THREAD

**Issue by alexlii1971** [Jigsaw-Code/outline-sdk#194]
Hello,

We have a server in China, and the server with Ubuntu is limited to access any global resource.

So, is there any way to run outline client on Linux terminal by command line?

Thanks

**Comment by cinsort** [comment]
Hi @jyyi1, having troubles running previous command on Ubuntu 22.04:
```
# github.com/Jigsaw-Code/outline-sdk/network/lwip2transport
go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.11/network/lwip2transport/device.go:35:13: undefined: lwip.LWIPStack
go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.11/network/lwip2transport/device.go:83:15: undefined: lwip.NewLWIPStack
go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.11/network/lwip2transport/device.go:90:7: undefined: lwip.RegisterOutputFn
```

**Comment by jyyi1** [comment]
Hi @cinsort , this seems to be a Go or C/C++ compiler issue. We are using a native LwIP network stack defined here: https://github.com/eycorsican/go-tun2socks/blob/master/core/lwip.go#L21-L25 . That requires `CGO_ENABLED=1` and a native C/C++ compiler installed in the system. And also `GOOS` needs to be `linux` as well.

You may confirm these setting by running `go env`. Also, please use `go` version `1.21+` to run the command.

**Comment by ElGrats** [comment]
> Hi @cinsort , this seems to be a Go or C/C++ compiler issue. We are using a native LwIP network stack defined here: https://github.com/eycorsican/go-tun2socks/blob/master/core/lwip.go#L21-L25 . That requires `CGO_ENABLED=1` and a native C/C++ compiler installed in the system. And also `GOOS` needs to be `linux` as well.
> 
> You may confirm these setting by running `go env`. Also, please use `go` version `1.21+` to run the command.

and what to do?

**Comment by ElGrats** [comment]
[ERROR] 2024/05/28 05:30:05 failed to configure system DNS: failed to backup DNS config file '/etc/resolv.conf.head' to '/etc/resolv.head.outlinecli.backup': rename /etc/resolv.conf.head /etc/resolv.head.outlinecli.backup: no such file or directory

**Comment by jyyi1** [comment]
> [ERROR] 2024/05/28 05:30:05 failed to configure system DNS: failed to backup DNS config file '/etc/resolv.conf.head' to '/etc/resolv.head.outlinecli.backup': rename /etc/resolv.conf.head /etc/resolv.head.outlinecli.backup: no such file or directory

Hi @ElGrats , this is a known issue and there is a PR to fix it: https://github.com/Jigsaw-Code/outline-sdk/pull/203. It's not quite ready yet, but feel free to contribute to it!

In the meantime, you can work-around the problem by creating an empty file named `/etc/resolv.conf.head`.

**Comment by adequacy1** [comment]
What do I do with this error?
```
# go run github.com/Jigsaw-Code/outline-sdk/x/examples/outline-cli@latest -transport "ss://Y2hhY2hh[...hidden...]wNzU0#127+%D0%92%D1%81%D1%8F%D0%BA%D0%B8%D0%B9"
OutlineVPN CLI (experimental)
[INFO] 2024/07/24 22:06:25 updated global IPv6 support: false
[INFO] 2024/07/24 22:06:25 updated global IPv6 support: true
[ERROR] 2024/07/24 22:06:25 failed to create OutlineDevice: invalid server hostname: lookup Y2hhY2hh[...hidden...]wNzU0: no such host
```
It looks like it's trying to resolve the entire encoded string as a hostname.

**Comment by jyyi1** [comment]
Hi @adequacy1 , please make sure you are using a valid Outline access key (example key: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo1UkVmeFRqbHR6Mkw@outline-server.example.com:17178/?outline=1`). I don't see any `@` or `:` or port numbers in your key, and they are all required.

**Comment by adequacy1** [comment]
Got it. This is the key to VPN Generator (vpngen.org). I thought it was your colleagues. But no, they changed the format of the key and thus made it impossible to use them on many linux distributions.

**Comment by jyyi1** [comment]
I see, we don't have any information about vpngen.org. It's possible their new keys don't work with Outline. For troubleshooting, check the source code here: https://github.com/Jigsaw-Code/outline-sdk/blob/main/x/examples/outline-cli/app_linux.go

Maybe double check your DNS settings (no internet if using a local DNS like 192.168.x.x) and, whether the server supports 
 TCP/UDP over Shadowsocks.

**Comment by adequacy1** [comment]
Now vpngen.org has corrected the issuing of keys and they started to work normally with outline-cli. But I found it more convenient to use shadowsocks-rust client in socks-proxy mode (the same keys work with it). Thank you for your answers, it made a lot of sense!

**Comment by jyyi1** [comment]
Thanks for the information, I will close this issue.
