### ISSUE TITLE
Commit 49ebf7c is breaking `httpproxy` with `ss` dialer

### ISSUE THREAD

**Issue by amircybersec** [Jigsaw-Code/outline-sdk#210]
I am not so sure what is causing this but this commit is breaking `httpproxy` with `ss` transport.

https://github.com/Jigsaw-Code/outline-sdk/commit/49ebf7c26e14fff3296dc93c0cb63cd4ad32bab1

## Background

The current `fyne-proxy` implementation in examples works with the following `go.mod` setup 

```
require (
	fyne.io/fyne/v2 v2.4.3
	github.com/Jigsaw-Code/outline-sdk v0.0.12-0.20240117212231-233d1898e1db
	github.com/Jigsaw-Code/outline-sdk/x v0.0.0-20240117212231-233d1898e1db
)
```

I upgraded SDK to version `v0.0.15` and re-tested it and it still functioned properly.

```
➜  go get github.com/Jigsaw-Code/outline-sdk@latest
go: upgraded github.com/Jigsaw-Code/outline-sdk v0.0.12-0.20240117212231-233d1898e1db => v0.0.15
go: upgraded golang.org/x/crypto v0.17.0 => v0.18.0
go: upgraded golang.org/x/net v0.19.0 => v0.20.0
go: upgraded golang.org/x/sys v0.15.0 => v0.16.0

➜ go mod tidy
require (
	fyne.io/fyne/v2 v2.4.3
	github.com/Jigsaw-Code/outline-sdk v0.0.15
	github.com/Jigsaw-Code/outline-sdk/x v0.0.0-20240117212231-233d1898e1db
)
```
## How to reproduce:
However after updating `x` to the latest version `fyne-proxy` stops working:

```
> go get github.com/Jigsaw-Code/outline-sdk/x@latest
> go mod tidy
require (
	fyne.io/fyne/v2 v2.4.3
	github.com/Jigsaw-Code/outline-sdk v0.0.15
	github.com/Jigsaw-Code/outline-sdk/x v0.0.0-20240402215738-49ebf7c26e14
)
```
Then use a valid `ss` link to connect. Nope that the issue is related to `httpproxy` package used in `fyne-proxy` example. I am using `fyne-proxy` since it is easier for debugging.

### Extra context and debugging efforts:

1. please note that if I use `split:1` or `tlsfrag:1` to configure the transport, the proxy works fine. However it breaks if I use `ss` transport. Using wireshark, I see a lot of `TCP Acked Unseen segment` messages.

<img width="1292" alt="Screenshot 2024-04-03 at 10 26 17 AM" src="https://github.com/Jigsaw-Code/outline-sdk/assets/117060873/8e6ba096-e310-4d84-8c1e-b797121c9bbf">

2. If the 'x' package is rolled back to `github.com/Jigsaw-Code/outline-sdk/x v0.0.0-20240402154916-48d8a48b34a6` version, which is one commit behind 49ebf7c, the issue disappears.

**Comment by paingpp343224** [comment]
> I am not so sure what is causing this but this commit is breaking `httpproxy` with `ss` transport.
> 
> [49ebf7c](https://github.com/Jigsaw-Code/outline-sdk/commit/49ebf7c26e14fff3296dc93c0cb63cd4ad32bab1)

**Comment by paingpp343224** [comment]
Connect

**Comment by fortuna** [comment]
I was able to reproduce. The easiest way is to run:

```sh
go run github.com/Jigsaw-Code/outline-sdk/x/examples/http2transport@49ebf7c, -transport "$KEY"
```

Then test:

```sh
curl -p -x localhost:1080 http://ipinfo.io
```

The previous commit works fine:

```sh
go run github.com/Jigsaw-Code/outline-sdk/x/examples/http2transport@48d8a48 -transport "$KEY"
```

I'm investigating

**Comment by fortuna** [comment]
It seems the code is getting stuck on both reading the client connection (to write to the target) and reading the target connection (to write to the client) I still don't understand why.

Stuck reading the client connection (using the http connReader):
![image](https://github.com/Jigsaw-Code/outline-sdk/assets/113565/0d465d16-9376-4d50-b1d2-4163d9b92b57)

Stuck on reading the target connection (over Shadowsocks):
![image](https://github.com/Jigsaw-Code/outline-sdk/assets/113565/23de076b-0acf-4b71-b1a3-993414aa25cb)

**Comment by fortuna** [comment]
I understand the bug now.

The problem is that the bufio.ReadWriter returned by the http.Hijacker does not immediately flush the contents on writes. And io.Copy doesn't flush the contents after each Write. This way the initial Shadowsocks data is never sent to the proxy, which keeps waiting. There's also nothing to read from the connections, that's why they are stuck.

One possible workaround is to call the bufio.ReadWriter ReadFrom method instead. This is what io.Copy ends up doing for connections that don't implement WriteTo. Our Shadowsocks connections implement WriteTo, which takes over, but other transports don't, that's why they are unnaffected.

Fix to come next.
