### ISSUE TITLE
doesn't work in Ubuntu 24

### ISSUE THREAD

**Issue by Igor-Shabalin** [Jigsaw-Code/outline-sdk#244]
Hi

This is my problem

go: downloading github.com/Jigsaw-Code/outline-sdk/x v0.0.0-20240530210837-c99a7ce98297
go: downloading github.com/Jigsaw-Code/outline-sdk v0.0.16
go: downloading github.com/Jigsaw-Code/outline-sdk v0.0.15
go: downloading github.com/songgao/water v0.0.0-20190725173103-fd331bda3f4b
go: downloading github.com/vishvananda/netlink v1.1.0
go: downloading golang.org/x/sys v0.16.0
go: downloading golang.org/x/net v0.20.0
go: downloading github.com/eycorsican/go-tun2socks v1.16.11
go: downloading github.com/shadowsocks/go-shadowsocks2 v0.1.5
go: downloading golang.org/x/crypto v0.18.0
go: downloading github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df
# github.com/Jigsaw-Code/outline-sdk/transport
go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.15/transport/happyeyeballs.go:90:29: error: reference to undefined identifier ‘atomic.Int32’
   90 |                 var pending atomic.Int32
      |                             ^
go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.15/transport/happyeyeballs.go:194:52: error: reference to undefined identifier ‘errors.Join’
  194 |                                 lookupErr = errors.Join(lookupErr, lookupRes.Err)
      |                                                    ^
go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.15/transport/happyeyeballs.go:242:50: error: reference to undefined identifier ‘errors.Join’
  242 |                                 dialErr = errors.Join(dialErr, dialRes.Err)
      |                                                  ^
note: module requires Go 1.20

pi@hp:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

**Comment by ed-asriyan** [comment]
> note: module requires Go 1.20

what version of Go is installed?

**Comment by Igor-Shabalin** [comment]
> > note: module requires Go 1.20
> 
> what version of Go is installed?

pi@hp:~$ go version
go version go1.18 gccgo (Ubuntu 14-20240412-0ubuntu1) 14.0.1 20240412 (experimental) [master r14-9935-g67e1433a94f] linux/amd64

**Comment by Igor-Shabalin** [comment]
Sorry . With go 1.20  working good :)
