### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sasanmcp** [Jigsaw-Code/outline-sdk#249]
here is the output when I try to build the client:

~/outline-sdk/x/examples$ go build -o outline-cli ./outline-cli
\# github.com/Jigsaw-Code/outline-sdk/transport
../../../go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.16/transport/happyeyeballs.go:90:22: undefined: atomic.Int32
../../../go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.16/transport/happyeyeballs.go:194:24: undefined: errors.Join
../../../go/pkg/mod/github.com/!jigsaw-!code/outline-sdk@v0.0.16/transport/happyeyeballs.go:242:22: undefined: errors.Join
note: module requires Go 1.20

what's wrong with all those modules?

**Comment by sbruens** [comment]
You might be using an old version of Go. Please update your version and try again.
