### ISSUE TITLE
сайт не работает с вашим впн

### ISSUE THREAD

**Issue by NataliPre** [Jigsaw-Code/outline-sdk#281]
Я сегодня купила платную подписку на месяц, внесла оплату, но сайт который нужно чтобы открывался та ки не работает.
Я прошу вернуть потраченные деньги мне обратно.

https://www.limango.de/

**Comment by NataliPre** [comment]
как связаться с поддержкой я не нашла, ваш впн меня не устраивает. хочу просто вернуть деньги. суток не прошло, но пользоваться услугой я не могу. деньги потрачены впустую

**Comment by sbruens** [comment]
The Outline team does not collect payment. Please contact the person who gave you the access key to address this issue.﻿
