### ISSUE TITLE
no route to anywhere after I run the CLI

### ISSUE THREAD

**Issue by sasanmcp** [Jigsaw-Code/outline-sdk#301]
I have a functional outline server which works for both android and windows client.
when I try to run the same key using outline-cli, it gets connected however there is no route to anywhere. I can't ping 8.8.8.8, nor anywhere else. I see an interface in linux if I run **ifconfig** but I don't see anything in my **route -n**. no DNS resolution, nothing works.

**Comment by jyyi1** [comment]
Hi @sasanmcp , thanks for reporting the issue.

Feel free to review the routing logic code: https://github.com/Jigsaw-Code/outline-sdk/blob/main/x/examples/outline-cli/routing_linux.go

And here is a more detailed explanation of the logic: https://github.com/Jigsaw-Code/outline-sdk/issues/138#issuecomment-1854796842.

**Comment by jyyi1** [comment]
Unfortunately, this is a developer tools, so we don't have a log of documentation. Feel free to checkout the source code and add logs to it:  https://github.com/Jigsaw-Code/outline-sdk/blob/main/x/examples/outline-cli/routing_linux.go
