### ISSUE TITLE
GPLv3

### ISSUE THREAD

**Issue by ignoramous** [Jigsaw-Code/outline-sdk#325]
#252 adds [psiphon-tunnel-core](https://github.com/Psiphon-Labs/psiphon-tunnel-core) which is GPLv3, which makes this repository GPLv3?

afaik, (unlike MPLv2) Apache v2 (the [current license](https://github.com/Jigsaw-Code/outline-sdk/blob/8f915062890c18737a1955a09e1fede4fd5c7806/LICENSE)) isn't compatible with GPLv3, so unsure if those two can mix in case two different binaries are built (so that resulting binaries can be licensed separately: GPLv3 for the flavour that includes Psiphon Core, Apache for one which doesn't).

Additionally, GPLv3 isn't compatible with Apple AppStore T&C: ([an old thread](https://forums.developer.apple.com/forums/thread/18922) / [archive](https://ghostarchive.org/archive/KBA9g)). This may or may not be desirable.

cc: @adam-p #251

**Comment by fortuna** [comment]
@ignoramous We don't distribute GPL code or binaries built from GPL code, so our code does not need to be GPL.
The GPL dependencies are only pulled if you add the `psiphon` tag.

It's up to the developer using the SDK to decide whether to pull Psiphon or not. If they do, they will need to be GPL, if they don't, then not necessarily.

**Comment by ignoramous** [comment]
Thank you.

I don't know how I missed the pkg's godoc.
