### ISSUE TITLE
Python SDK For Telegram Bots

### ISSUE THREAD

**Issue by MartinHennrich** [Jigsaw-Code/outline-sdk#84]
What do you think about an Outline Python SDK that could be used for [Telegram bots](https://core.telegram.org/bots).
I like to use [pyTelegramBotAPI](https://pypi.org/project/pyTelegramBotAPI/).

**Comment by fortuna** [comment]
While utilities to build bots can be helpful for access distribution, our SDK is focused on networking utilities, so bot utilities are out of scope out of scope. Unless they were used to facilitate connections somehow.
